### PR TITLE
Creating logic to update slot codes if dates change

### PR DESCRIPTION
**Pull request by shwarnock**
Sorry for all the back and forth. I believe this one is signed properly!

### CODE REVIEW

**Comment by shwarnock** [comment]
pre-commit.ci autofix

**Comment by shwarnock** [comment]
Just a heads up, allowing the pre-commit to autofix creates an unverified commit

**Comment by shwarnock** [comment]
@tykeal Can you help me with this glint failure. Seems to be an issue with the commit title?

**Comment by tykeal** [comment]
> @tykeal Can you help me with this glint failure. Seems to be an issue with the commit title?

I mentioned this on the other change, but I have a requirement for semantic (conventional) commit messages. As such, your commit message subjects are not meeting the standard.

Your first commit should be:

`Feat: Creating logic to update slot codes if dates change`
 
Or better:

`Feat: Date based slot code updates on date change`

The second commit should really just be squashed into the first one and then you will need to force push the updates back.

**Comment by tykeal** [comment]
BTW if you setup pre-commit locally you'll get all the those checks locally before you even push up to GH for validation.

**Comment by shwarnock** [comment]
> BTW if you setup pre-commit locally you'll get all the those checks locally before you even push up to GH for validation.

Perfect, I will try to get that setup locally

**Comment by tykeal** [comment]
@shwarnock just letting you know, I've applied the PR to my test instance and it's having a lot of issues. I'll have more details in a bit for you, but just letting you know that the implementation as it currently exists fails completely for many of the use cases that the integration has.

**Comment by shwarnock** [comment]
@tykeal thanks for checking! Please let me know the uses cases so I can check them out locally. I only was able to test my use case.

**Comment by tykeal** [comment]
@shwarnock given the amount of changes and testing I needed to do I ended up rewriting the entire PR. See #225 for what I did

**Comment by tykeal** [comment]
FYI I have just released v1.2.0 with this new feature in it.

**Pull request closed without merging**
